// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5m0OAdNULZqR0GXodHaCjfH6uCkOhG8',
    appId: '1:219739054688:web:cff96d98c4e32d3474d905',
    messagingSenderId: '219739054688',
    projectId: 'menufinder-ed27e',
    authDomain: 'menufinder-ed27e.firebaseapp.com',
    storageBucket: 'menufinder-ed27e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5m0OAdNULZqR0GXodHaCjfH6uCkOhG8',
    appId: '1:219739054688:android:76d3b645b28886b074d905',
    messagingSenderId: '219739054688',
    projectId: 'menufinder-ed27e',
    storageBucket: 'menufinder-ed27e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5m0OAdNULZqR0GXodHaCjfH6uCkOhG8',
    appId: '1:219739054688:ios:cdab2b8c84e101e874d905',
    messagingSenderId: '219739054688',
    projectId: 'menufinder-ed27e',
    storageBucket: 'menufinder-ed27e.firebasestorage.app',
    iosBundleId: 'com.qrmenufinder.qrMenuFinder',
  );
}
